### ISSUE TITLE
what is delme file

### ISSUE THREAD

**Issue by agarwal** [biocaml/biocaml#152]
In 0e55e8d0aabfc102b9e1d5e1cbada42e64f471b1, I added the `delme` file to .gitignore because it was created when I ran the tests. In 6c32d79df295b3a9efb83c3acb0b6a143cbea515, I see that this file was named in a now deleted line, but this line in no way should have created the file. And running the tests now doesn't create the file anymore, so I'm unsure what happened. Is this file created by us or by OUnit? Do we still need to have it in .gitignore? @pveber I suspect you might know the answer.

**Comment by pveber** [comment]
Yeah, I know it because it is I who left that mess behind :o)! The deleted line doesn't create a `delme` file but two line after it does. I guess I left that because at some point I wanted to see the temp file that is generated in the test, and forgot afterwards to fix that. Sorry about that! I guess we can remove `delme` from `.gitignore`.

**Comment by agarwal** [comment]
IIUC, you were overriding the temp filename created by `Utils.with_temp_file`, but now are not. So now the `delme` files isn't created. Ok, got it. So removing it from .gitignore.
