### ISSUE TITLE
'remove' field in opam

### ISSUE THREAD

**Issue by pveber** [biocaml/biocaml#165]
```
$ opam-publish submit biocaml.0.5.0
[v0.5.0.tar.gz] https://github.com/biocaml/biocaml/archive/v0.5.0.tar.gz downloaded
[ERROR] In biocaml.0.5.0/opam:
          warning 27: No field 'remove' while a field 'install' is present, uncomplete uninstallation suspected
```
--> Check uninstall works

**Comment by agarwal** [comment]
This warning is a bit annoying. We don't need an `remove` section because we follow good practice by letting the install be fully defined by a `.install` file. However, we do have an `install` section, which generates this file (and META).

I recently decided to move the commands currently in `install` into `build`, thus eliminating the `install` section too. I guess that is semantically reasonable. The `install` section should really do the installing, not just generate the files necessary to do the install.

**Comment by pveber** [comment]
Followed your suggestion, thanks!
